seq = 'GGTCTAGTGCCTAGTGCATGCTAGTGCCTAGTGCGTGCCCGCGCCCCCTAGTGCTTCTAGTGCAACGATAACTAGTGCGCTAGTGCCTAGTGCCCTAGTGCAACTAGTGCCGAACTAGTGCTATCTAGTGCTTGCTAGTGCCTAGTGCACGCTACTAGTGCCTAGTGCGTACCCTAGTGCCGCCCCTAGTGCCCCCTAGTGCCTTATCTAGTGCACTAGTGCCTAGTGCCTTCGACCCTAGTGCGGCTAGTGCCTAGTGCGACTAGTGCGCCCTACTGCTAGTGCTCCTAGTGCCTAGTGCTACTAGTGCGGTGCTAGTGCCTAGTGCCTTGGCTAGTGCGAAAACGCCTAGTGCCTAGTGCCCGTCTAGTGCACCTAGTGCAAACCGGTTAACCTAGTGCCTAGTGCCTCTAGTGCACTAGTGCACTCGGCCCTAGTGCGATCTAGTGCGTCTAGTGCAGCTAGTGCATGCTAGTGCTGAGGGCAACTAGTGCATCTTGCTGCCTCCTAGTGCTGTCTAGTGCTCTAGTGCCATACTAGTGCGCTAGTGCCTAGTGCTCCCTAGTGCTAAGGCTAGTGCCTGCTAGTGCACTAGTGCGAGTCAATTACTAGTGCATCTAGTGCGCCTAGTGCGGCGCTAGTGCACTAGTGCGGGCTCTAGTGCCTAGTGCTCCCACTCTAGTGCTGGCTAGTGCAAGCCTAGTGCCTAGTGCCGCCATCCTAGTGCCTAGTGCGGTCTAGTGCTCTAGTGCGCGCTCACGCTAGTGCCCTAGTGCGACTAGTGCCTAGCCTAGTGCGTCTAGTGCATCTAGTGCCGCTAGTGCCTAGTGCCCTAGTGCCTAGTGCGTCTAGTGCGCTAGTGCCTAGTGC'
motif = 'CTAGTGCCT'

def find_all(a_seq, a_motif):
    start = 0
    while True:
        start = a_seq.find(a_motif, start)
        if start == -1:
            return
        yield start + 1 # add 1 to compensate for 0-based numbering
        start += 1

motif_count = list(find_all(seq, motif))

joined_string = ' '.join([str(v) for v in motif_count])
print(joined_string)

file = open('motif_ans.txt', 'w+')
file.write(joined_string)
